### ISSUE TITLE
[Feature Request] Option to specify path to manifest.json

### ISSUE THREAD

**Issue by T1mL3arn** [mozilla/web-ext#1034]
### Is this a feature request or a bug?
Feature Request

### What is the expected or desired behavior?
Option like `--manifest-path` to specify relative(or absolute) path to `manifest.json` when running an extension. 

FF allows to load temp addon (from about:debugging page) by picking manifest file directly. So `web-ext` could support this too. It will be convenient for situation when there is a few manifest.json files with names like `mozilla-manifest.json` and `opera-manifest.json`.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to submit an issue. I don't think this option would be helpful because the file must be named `manifest.json` for [your extension to be valid](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension). Also, you can already use [`--source-dir`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--source-dir_-s) to set the location of the folder containing `manifest.json`. To support two different manifests you'd have to put them in different directories. Example: `build/firefox/manifest.json` and `build/opera/manifest.json`.

**Comment by T1mL3arn** [comment]
As I understood, `--source-dir` sets *whole* addon directory, so is need to store copies of other resources like images, scripts or whatever. It is definitely not an option. 

`web-ext` could do renaming manifest file on its own side, for validity. For now it is possible to use console(or  any appropriate script) to rename manifest file and put it (with the other resources) to dest bin-like folder, which later will be sent to `web-ext` as `--source-dir`.

If in the future `web-ext` will allow to run addon in Chrome-like browser, then might be issue how to do it - a command to set chrome-related folder (with unnecessary duplications of resources) or just a command to specify manifest file.

**Comment by kumar303** [comment]
> As I understood, --source-dir sets whole addon directory, so is need to store copies of other resources like images, scripts or whatever. It is definitely not an option.

I was envisioning that you would introduce a build step that creates each extension directory (one for Firefox, one for Chrome, etc), each built from the same source. With that approach, `--source-dir` should work fine. My rationale for this approach was that you will have to build a custom directory for each browser extension anyway since the manifests are different.

Don't hesitate to file more issues as you work through it and discover shortcomings with web-ext.

You are right, we will have to figure this out when supporting Chrome. However, it is possible to do a lot of things with *one* manifest file between both Chrome and Firefox.
