### ISSUE TITLE
web-ext start is slow (4-5 seconds for --help or --version)

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1301]
It takes an excessive amount of time before `web-ext` starts its program logic.
Even simple commands like `web-ext --help` or `web-ext --version` take 4-5 seconds to run on my Linux machine.

**Comment by rpl** [comment]
@Rob--W I looked at the nodejs profile data while running `web-ext --help` and most of the time is spent in v8 C++ code and js code part of the nodejs internals related to the module loading.

I bet that a pretty big improvement of the startup time can be easily achieved by loading the command modules lazily instead of importing all of them statically before processing the command line arguments (and we currently import all of them in two places: in the 'main' module to export them as an "exposed API", and in the 'program' module which uses it to run the command selected by the command line arguments).
