### ISSUE TITLE
Read file-ignore rules from a config for building XPIs

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#131]
https://github.com/mozilla/web-ext/issues/85 added some simple defaults for ignoring files when building an XPI. Let's look for a config file inside a web extension that the developer can use to declare custom rules.

JPM looked for `.jpmignore` but I think it would be more flexible if we looked for a global `web-ext.config` (or something) and allowed that to set default values for any command line option. We could add an option to `build` like `--ignore-filenames=*.zip,*.foo` so that a config file could declare the same `ignore-filenames` defaults. Yargs [has support for config files](http://yargs.js.org/docs/#methods-configkey-description-parsefn).

See https://github.com/mozilla/web-ext/issues/176 for general config file support.

**Comment by kumar303** [comment]
Let's do the general config file logic first: https://github.com/mozilla/web-ext/issues/176

**Comment by kumar303** [comment]
This seems pretty important. It looks like some people are putting `sign.sh` (which includes API keys) in the root of their project. This will get included in an XPI by default.

**Comment by lidel** [comment]
I have use case that would greatly benefit from adding `--ignore-filenames=*.zip,*.foo` parameter support to both `build` and `lint`.

The add-on I am building relies on "browserified" and "minimized" NPM libraries which need to be included during `build` but produce a lot of warnings when I run `lint`.  
Due to this I often just ignore `lint` output -- too noisy to analyze every time. 

Excluding these 3rd party artifacts from `lint` would improve the situation, as I could focus on removing any warnings from the code I control.

**Comment by kumar303** [comment]
Note to self: when we document this we should link to this cheat sheet for how glob patterns work: https://github.com/isaacs/node-glob#glob-primer

**Comment by rpl** [comment]
@kumar303 additional note: when we document this we should mention that glob patterns (e.g. like `"node_modules/**"`) needs to be quoted to prevent the shell to expand the glob pattern into the entire list of files that verify the glob pattern.

**Comment by kumar303** [comment]
Here is the documentation. @rpl or anyone, let me know if anything is unclear or needs tweaks: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--ignore-files_-i

**Comment by kumar303** [comment]
or @eight04  too! ^
