### ISSUE TITLE
Firefox in headless mode

### ISSUE THREAD

**Issue by NivedhaSenthil** [mozilla/web-ext#1337]
Can we start firefox in headless mode to load extension using webext ? 
Dint see any options in documentation. 

If it is not already there, then it would be a good feature to get in.

**Comment by Rob--W** [comment]
`web-ext run` does not seem to support headless mode yet.

Why do you want to have headless mode though? It seems a bit difficult to debug extensions without visible window.

**Comment by NivedhaSenthil** [comment]
I was trying to create an automation tool to test webpages using extensions, was able to do it by loading the browser. Thought will be good if we can run tests in headless mode also.

**Comment by kumar303** [comment]
Hi @NivedhaSenthil. web-ext currently doesn't support this type of automated testing.

There is an older repo with an example of how to achieve the kind of automated testing you describe but probably not with a headless browser. https://github.com/Standard8/example-webextension/ (see https://github.com/Standard8/example-webextension/blob/master/docs/Functional.md)

I'm not sure if such a feature is in scope for web-ext since there are already tools like Selenium that have first class support for add-ons. This feature does get requested a lot, though, especially for add-ons that need to detect when a site they depend on changes.

**Comment by NivedhaSenthil** [comment]
Thanks for the response. Will check  https://github.com/Standard8/example-webextension/ if it can help anyways

**Comment by rpl** [comment]
@NivedhaSenthil the following fragment from our webextension-polyfill repository shows how we are configuring selenium-webdriver to start Firefox in headless mode and install an extension temporarily into it:

https://github.com/mozilla/webextension-polyfill/blob/ea82fbf55684193c10e81545378a7656a0871840/test/integration/setup.js#L53-L73

and so it may be helpful to achieve what you want.

In the meantime, I'm closing this issue because, as Kumar, I still feel that this feature may be a bit out of scope for the web-ext tool itself, and it can be better achieved using selenium webdriver.
