### ISSUE TITLE
Replace NPM Token

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/web-ext#1344]
Since all NPM upload tokens have been revoked a new one needs to be created and added to travis.yml

**Comment by Rob--W** [comment]
These tokens were revoked because of a backdoor in `eslint-scope@3.7.2` that stole the content of `~/.npmrc: https://status.npmjs.org/incidents/dn7c1fgrr7ng

This affected any installation of `eslint-scope@3.7.2` for two hours last thursday (12 July 2018). For the exact timeline, see https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

We currently depend on `babel-eslint@8.2.5`, which depended on `eslint-scope@~3.7.1`. If there are any other secrets in your `~/.npmrc` AND you pulled in `eslint-scope@3.7.2`, treat the secret as compromised and refresh any tokens if needed.
