### ISSUE TITLE
Feature request: add command line option to disable line rewriting

### ISSUE THREAD

**Issue by hexpunk** [mozilla/web-ext#1375]
https://github.com/mozilla/web-ext/issues/617 added this line rewriting trick using the carriage return (`\r`).

https://github.com/mozilla/web-ext/blob/ecb3ecc989f062b1ae795c92a040a1b6434a4486/src/firefox/remote.js#L181-L182

However, this causes problems when using web-ext with [concurrently](https://github.com/kimmobrunfeldt/concurrently), for example.  (See https://github.com/kimmobrunfeldt/concurrently/issues/168)

Can I suggest adding a command line option that prevents this line from being overwritten (or more accurately, adds a newline like what currently happens in verbose mode)?  This is similar in my mind to the `--preserveWatchOutput` option in the Typescript compiler which disables it from clearing the console before each recompilation while in watch mode.

**Comment by rpl** [comment]
@JayAndCatchFire as you mentioned in the concurrently issue linked above, it may be not that unlikely that other commands could have the same issue with concurrently, because of this kind of behavior, and so it seems to me that it may be more reasonable to fix the issue on the concurrently side once, so that it does not stop to work because of that.

In the meantime, as a workaround for your specific use case, you may try to write a small nodejs script that use web-ext as a library, which makes web-ext silent (from a concurrently point of view) and logs its own messages (some that don't make concurrently unhappy ;-))

You can take a look to https://github.com/hiikezoe/web-ext-webpack-plugin/blob/master/web-ext-webpack-plugin.js as an example of how web-ext can be used as a nodejs library.
