### ISSUE TITLE
Create a Web Version for Web-Ext

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/web-ext#1402]
### Is this a feature request or a bug?
Feature

### What is the current behavior?
npm package is good for CLI use, it's good to have also a web version which delivers the same functionality.

### What is the expected or desired behavior?
To create a GUI based web version for web-ext for easy access. This will give easy access for many across web, especially newbies.

Created a github repo to track the development.
https://github.com/ranjithrajv/web-ext

**Comment by rpl** [comment]
@ranjithrajv thanks for letting us know about your initiative.

I'm closing this issue as invalid because a "web ui" version of web-ext tool is out of the scope for this project as an integrated feature.

Nevertheless the web-ext npm package can also be used as a library and embedded into a separate tool that could expose its features (as an example, linting may be one of those) through a web UI (e.g. integrated in a "Electron or NW.js" based desktop application or in the form of a locally executed web-server, etc.) instead of the default web-ext CLI UI.
