### ISSUE TITLE
Add ways for extensions to see "runtime" configuration datarable from command line

### ISSUE THREAD

**Issue by gregglind** [mozilla/web-ext#1406]
### Is this a feature request or a bug?

Feature Request

### What is the current behavior?

web-ext run has a `--prefs` command.  This is useful for configuring testing and other parameters.

However, so far as I can tell, extensions cannot see those preferences.

#### Who cares, or Tl;dr for out of code configuration

- demo-ing different branches of novel ui without having to recompile / re-sign the addon.
- CI/Testing  extensions under different state scenarios

#### Three solutions 

1.  some solution that allows 'at install' configuration.  Amazon Assistant figured things like partner code out by seeing the last open url (the download url) and pulling fields out of that url.  This seems hacky.
2. make extension be able to read a special / magic prefs tree 
 - based on their id,
  -  only defined for extensions with an Id,
  - using makeWidgetId rules
3.  Enhance web-ext run with a '--storage' flag (clone of --prefs) .   This would write to `browser-extension-data/<extensionId>/storage.js` before installing the extension.

(both together are even more awesome).

**Comment by kumar303** [comment]
Hi @gregglind, thanks for taking the time to file an issue. 

> web-ext run has a `--prefs` command ... However ... extensions cannot see those preferences.

As far as I know, that is intentional. I believe it is to protect users from accidentally installing an extension that can read their preferences.

In any case, this feature seems out of scope for web-ext. The web-ext tool can run an extension but it does not provide any runtime services.

You mentioned that you would like this feature for testing; it might still be possible. This solution comes to mind but maybe there is a better way:
* Create a custom script that executes `web-ext run` (it could just be a shell script)
* Use a JSON or text (or whatever) file to list all of the prefs you want to set
* Have your custom script read that text file when generating the `--pref` part of the `web-ext run` command
* Include the text file in your extension's own assets so it can be read at runtime

**Comment by gregglind** [comment]
(I claim that doesn't solve the problem, because pure extensions cannot
read prefs.
Thus my suggestion about `--storage` (or `managed`), so that the extension
can see something that it has an api for.)

**Comment by kumar303** [comment]
I'm happy to discuss it further in case I misunderstood.

> I claim that doesn't solve the problem, because pure extensions cannot read prefs.

How does it not solve it? Instead of "reading prefs" directly from the browser, the solution I proposed would have your extension read an internal file, such as `source-to-extension/assets/my-web-ext-run-prefs.json`. This file would also be used in your run script like `web-ext run --pref ${prefsFromJSON}`. When your extension itself is running, it could read `assets/my-web-ext-run-prefs.json` from a [local asset](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources) to know what prefs were set.

In any case, I closed the issue only because it doesn't seem like a feature well suited for web-ext. The web-ext tool is for developing extensions, not enhancing extensions with runtime features.

> Enhance web-ext run with a '--storage' flag (clone of --prefs) . This would write to browser-extension-data/<extensionId>/storage.js before installing the extension.

It would be really hard to get this right because web-ext supports multiple versions of Firefox which might have differing formats and it's also quite different between platforms (Android, Windows, Linux, Mac).

**Comment by gregglind** [comment]
+1. Thank you for clarifying your proposed solution.  I will reflect on it.

I am trying to find solutions that allow distributing built / signed
extensions, while still allowing some runtime configuration.

**Comment by Rob--W** [comment]
You could create a Firefox profile with the desired default storage, and use the `--firefox-profile` (or the shorthand `-p`) with it.

To create the profile:

1. Create a new directory (e.g. `mkdir /tmp/newdir`), and start Firefox with it, e.g. `firefox --no-remote -profile /tmp/newdir`
2. Visit `about:config` and set `extensions.webextensions.keepStorageOnUninstall` to true, and also `extensions.webextensions.keepUuidOnUninstall` to true.
3. Install your test extension (or at least an extension with the same extension ID as your actual extension - see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID ).
4. Prepare the data that you want.
5. Uninstall the extension.

To use it afterwards: `web-ext run -p /tmp/newdir`
