### ISSUE TITLE
Add a complete-reload command line argument

### ISSUE THREAD

**Issue by thoughtsunificator** [mozilla/web-ext#1553]
I have an app that modifies the DOM and the current web-ext behavior is not working well with it.

**Comment by Rob--W** [comment]
If I understand your request correctly, you are asking for a way to automatically reload all tabs because content script changes are not undone when an extension unloads/reloads.

There are very few cases where reloading all tabs is the desired behavior, so we're not going to implement it, especially because you can just press F5 / Ctrl+R / Cmd+R to reload the page.

You can also consider rewriting your add-on to gracefully handle unloads/reloads by restoring the page at unload so that the next load of the extension works fine. This allows the add-on to function well if the user updates your add-on, which causes content scripts to be reloaded as well.
For an example of how you can develop logic to run when a content script unloads, see https://stackoverflow.com/a/47361379

If I misunderstood your request, please clarify what you meant.
