### ISSUE TITLE
Clicking link with target="_blank" in Android doesn't work PLUS it breaks debugging and whole add-on

### ISSUE THREAD

**Issue by icl7126** [mozilla/web-ext#1592]
### Is this a feature request or a bug?
Bug

### What is the current behavior?

See the video:
https://www.youtube.com/watch?v=RxWO3wykTLA

But basically this is what is happening:
1) create any addon page
2) insert any link on that page with target="_blank" attribute
3) open the add-on page in Android
4) click the link
5) link is NOT opened and add-on get's broken, debugging doesn't work anymore

### What is the expected or desired behavior?
Link should get opened.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v12.0.0
6.8.0
3.0.0

**Comment by Rob--W** [comment]
This is because the `browser.link.open_newwindow` pref is overridden, changed from default 3 to 2.

Unfortunately, there is also a bug in `web-ext run` for Android that `--pref=browser.link.open_newwindow=3` does not override the pref.

So as a work-around, visit `about:config` and reset the `browser.link.open_newwindow` preference (there is a Reset button that will restore the value of 3).

PS. Thanks for the detailed video. It made it much easier to see and debug the issue.
