### ISSUE TITLE
Cannot consistently start chromium on macOS

### ISSUE THREAD

**Issue by jezhou** [mozilla/web-ext#1779]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When I run `web-ext run --target chromium`, it doesn't seem to correctly start the Websocket server, which prevents Chrome + the extension from launching. This also happens when I run `npm test` in the web-ext project.

**Running web-ext test suite**
![70387504-92457d00-195a-11ea-9e95-d1e2a9a0db91](https://user-images.githubusercontent.com/7007623/70501323-9dbbb400-1ad2-11ea-9797-025f75332c62.png)

**Running web-ext cli with chromium**
![70387568-6080e600-195b-11ea-8410-52b25567be96](https://user-images.githubusercontent.com/7007623/70501324-9eece100-1ad2-11ea-8342-dc14b3d977e8.png)

Curiously, this will sometimes work if I use node v13.2.

![image](https://user-images.githubusercontent.com/7007623/70501793-efb10980-1ad3-11ea-9db9-21feadf3661c.png)

I have Chrome installed on my computer. Am I missing a step in the setup?

### What is the expected or desired behavior?

Websocket server is successfully started, and Chrome + the extension launches consistently.

### Version information (for bug reports)

`macOS`
10.14.6

`Chrome`
78.0.3904.108

`node --version && npm --version && npx web-ext --version`
v10.15.1, v13.2.0
6.11.3
3.2.1

**Comment by Rob--W** [comment]
`wss` is set at the start of `setupInstance`, at https://github.com/mozilla/web-ext/blob/7ee3c44365df645e49ef739590b2571c74c6d184/src/extension-runners/chromium.js#L93

The error is "Cannot read property 'address' of null", which implies that `wss` has become `null`. This only happens when `exit()` is called - https://github.com/mozilla/web-ext/blob/7ee3c44365df645e49ef739590b2571c74c6d184/src/extension-runners/chromium.js#L301

If this error occurs, then `exit()` has most likely been called, unexpectedly.

**Comment by rpl** [comment]
Interestingly it seems that we are triggering the same failure in the windows travis worker on an unrelated pull request (#1780): https://travis-ci.org/mozilla/web-ext/jobs/623117080#L682-L688
