### ISSUE TITLE
lint warns about Thunderbird API as "UNSUPPORTED_API "

### ISSUE THREAD

**Issue by joendres** [mozilla/web-ext#1826]
### Is this a feature request or a bug?
Bug

### What is the current behavior?

1. Make a WebExtension for Thunderbird that uses Thunderbird specific parts of the `browser` API like [browser.cloudFile](https://thunderbird-webextensions.readthedocs.io/en/latest/cloudFile.html).
1. Run `web-ext lint`
1. Get warnings like
> 
UNSUPPORTED_API         cloudFile.getAccount is not supported      This API has not been implemented by Firefox.

My  web extension source is at https://github.com/joendres/nextcloud-filelink.

### What is the expected or desired behavior?

Either web-ext could notice that manifest.json contains Thunderbird specific config like `cloud_file:`and not warn about usage of the corresponding API elements like `browser.cloudFile`.

Or there might be a config option to lint a Thunderbird extension that stops web-ext from warning about the Thunderbird API.

### Version information (for bug reports)

* **Thunderbird version**: 68.4.1
* **Your OS and version**: Windows 10 1909, Alpine Linux
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
12.14.1
6.13.4
4.0.0

**Comment by Rob--W** [comment]
The linter only knows about WebExtension APIs: https://github.com/mozilla/addons-linter/tree/a2f1917a35705cb89e3843e3994964ddda265daa/src/schema

I don't even know if Thunderbird is supported with web-ext. Is it?

**Comment by joendres** [comment]
As far as I understand the schemas are here: https://hg.mozilla.org/comm-central/file/tip/mail/components/extensions/schemas/

Yes, web-ext works well with Thunderbird and it's even recommended in Thunderbird's Addon debuging UI.

**Comment by rpl** [comment]
While most of web-ext feature would be probably working just fine on thunderbird, the `web-ext lint` command is based on the [addons-linter](https://github.com/mozilla/addons-linter) dependency, which we keep in sync with the WebExtensions API jsonschema files in mozilla-central periodically (when a new Firefox release does reach the beta channel).

And so this is technically an addons-linter issue, mozilla/addons-linter#3235 has been closed as out of scope for the mozilla/addons-linter repo, and because thunderbird does have a separate fork on the addons-linter at [thundernest/addons-linter](https://github.com/thundernest/addons-linter) where importing thunderbird schemas would fit better.

It looks that [thundernest/addons-linter](https://github.com/thundernest/addons-linter) is currently way behind the upstream `mozilla/addons-linter` repo, I'm not sure if  Thunderbird developers have plans for that repository (and keep it in sync with the upstream one and import Thunderbird schemas files periodically as we do for mozilla/addons-linter), but if they do update their fork then their package will provide an thunderbird-specific addons-linter cli tool that could be executed directly (instead of relaying on `web-ext lint`).
