### ISSUE TITLE
Should not reload on profile changes

### ISSUE THREAD

**Issue by gurupras** [mozilla/web-ext#1842]
#### Bug

`web-ext` clearly knows what the profile directory is (specified via `--firefox-profile`), and should not reload on changes to this directory. It shouldn't matter whether this directory is a child of the extension directory or not.

### What is the current behavior?

There are multiple ways of reproducing this bug, however, here's the one that was applicable to me.

  - Write an extension that sets up ports between content-script(CS) and background-script(BG) at `document_start`
  - Save this port in BG script in a variable
  - Start `web-ext` with a command-line similar to `web-ext run --keep-profile-changes --firefox-profile=.ff-profile/`
  - Navigate to any website, and attempt to send message from BG->CS using the saved variable
  - Observe error stating that the variable you saved earlier is `undefined`

### What is the expected or desired behavior?
Since a port was set up from a tab/frame during `document_start`, and saved in the BG script, this port should continue to be available. However, because this website updated your profile as it loaded, and in this _particular_ case, the profile directory is in the extension source directory, `web-ext` reloads the extension every time the profile is updated.

### Version information (for bug reports)

* **Firefox version**: 73.0
* **Your OS and version**: Ubuntu 18.04.3
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v12.14.1
6.12.1
4.0.0
````

**Comment by rpl** [comment]
I haven't tried yet to reproduce it locally but I'm pretty sure that `.ff-profile/` would also be likely bundled into the extension zip file by `web-ext build`, and in that case there is no `--firefox-profile` option to make the `web-ext build` command aware of it (and so to avoid that the developer would need to explicitly add `.ff-profile` to the files and directories to ignore during the extension zip file building).

Nevertheless, I think that it may be good to make `web-ext run --firefox-profile ...` to explicitly check if the firefox profile directory path is a descendant of the extension source directory and raise an explicit error to point out that the profile directory should not be a descendant of the extension source dir.

In the meantime, the `--ignore-files` should be able to workaround the issue for you (without the need to change the directory layout of the project).

**Comment by Rob--W** [comment]
The current reload logic is simple: If a file in the current directory has changed, then Firefox will be reloaded. I am against complicating the logic by checking whether a profile directory is in the current directory, because it adds complexity while there are still other unaddressed issues (e.g. `web-ext build` would also add the directory to the packaged extension, which is undesirable).

If you want to use `web-ext run` without this issue, use the `--no-reload` parameter. Then you are free to manually reload with the R key on demand. Alternatively, use the `--watch-file` option to only reload when a specific file is reloaded, instead of the whole directory and its files/directories within.
