### ISSUE TITLE
Temporary add-on installation is not supported in this version of Firefox

### ISSUE THREAD

**Issue by deweloprela** [mozilla/web-ext#1922]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
web-ext run --bc
Running web extension from /mnt/hgfs/p/t1
Use --verbose or open Tools > Web Developer > Browser Console to see logging

o: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.startFirefoxInstance (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:51601)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

### What is the expected or desired behavior?
It simple stop loading extension but it can be done through about:debugging#/runtime/this-firefox by loading temp addon, so not extension problem

### Version information (for bug reports)

* **Firefox version**:
77.0.1 (64-bit)
* **Your OS and version**:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
node --version && npm --version && web-ext --version
v8.10.0

Command 'npm' not found, but can be installed with:

sudo apt install npm

**Comment by Rob--W** [comment]
You're using an old version of `web-ext`. Update to the latest version instead - see #1921 (and #1884).

**Comment by deweloprela** [comment]
Ups sorry, had to check it before start this thread(

**Comment by deweloprela** [comment]
Any idia on how to install new version of web-ext? As i tried with sudo npm install web-ext@latest  and it seems don't like that i have node_modules folder in o extension i working on, after sudo npm -g uninstall web-ext --save-dev (i expect this command make web-ext forget about project) and npm uninstall web-ext still same result

**Comment by Rob--W** [comment]
First: NEVER use `sudo npm install`. It causes more harm than good. You can change the install location of your node modules with `npm config set prefix /home/youruser/.npm` for example

Then add the the location of `/home/youruser/.npm/bin` to your $PATH, so that anything you install can be found when you launch it from the terminal. For example:

```
# Add this to .bashrc
export PATH="/home/your user/.npm/bin":$PATH
```

From now on, anything that you install with `npm install` will become available, as expected.

Another way to use `web-ext` WITHOUT a global installation is to install it to your project. Then you can use the following to launch it:

```
./node_modules/.bin/web-ext ....
```

Yet another alternative is to use `npx run web-ext ...`

**Comment by deweloprela** [comment]
Ok finally done installation by 
apt purge npm 
than removing .npm folder in user home then installing npm again then 
npm install --global web-ext 
everything seems to work again. Thanks!
