### ISSUE TITLE
tests/functional/test.lib.imports.js fails intermittently due to "npm link"

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1961]
We had to restart the CI task of https://github.com/mozilla/addons-linter/pull/3250 multiple times because it failed intermittently, e.g. 

https://travis-ci.org/github/mozilla/addons-linter/jobs/708732203
https://travis-ci.org/github/mozilla/addons-linter/jobs/708732204

The relevant part is as follows and the regression was introduced in #1934 / 9c265a80054f155faa76fc1851b8437dac3aebd4 :

```
  1 failing

  1) web-ext imported as a library

       "before all" hook for "can be imported as an ESM module":

     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/mozilla/addons-linter/web-ext/tests/functional/test.lib.imports.js)
```

The `before` hook runs `npm link`. This will try to download & install dependencies, which is prone to causing intermittent failures, because 1) network is unpredictable and 2) resolving and installing dependencies via npm is slow.

**Comment by rpl** [comment]
In #1966 we added support for setting a custom mocha timeout using an environment variable, and then in the addons-linter we increased the mocha timeout using that variable and that fixed the intermittency of the functional tests due to this issue.

I haven't seen the same failure happening in the web-ext travis CI jobs yet, if we do notice that kind of failure in the future we can use the same environment variable to increase the timeout.

In the meantime I'm going to close this as fixed by #1966.
