### ISSUE TITLE
Improve visibility of message to enable "Remote Debugging via USB" with web-ext run -t firefox-android

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1969]
We have received multiple reports (e.g. #1899,  #1949 ) where the use thought that there was a bug in `web-ext run -t firefox-android`, while the real issue is that they forgot to enable "Remote Debugging via USB". We print a message with the instructions once:

https://github.com/mozilla/web-ext/blob/fc91c367723b8a7fb993c64927829aa66f9746d6/src/extension-runners/firefox-android.js#L585-L591

... but users still don't see this, e.g. because it is buried in the log files. We should improve the visibility of this instruction to help users with reminding that they need to enable this. For example, we could print the same message again when the connection continues to fail repeatedly.

**Comment by rpl** [comment]
Mentor: @rpl

**Comment by sonalprabhu** [comment]
Hi,
I am a beginner to open source. Can I try to work on this?

**Comment by rpl** [comment]
@sonalprabhu Sure, there isn't an existing pull request that is already covering fixing this issue and so you can definitely take a look at it and prepare a PR. Once you have submitted a pull request, we will mark this issue as `contrib: assigned`.

As Rob did mention in the issue description, we do already have a message that we show to remind the user to enable the "Remote Debugging via USB" (and the code where that is being done is also linked in the issue description), we want to show the same message again when the connection continues to fail or after web-ext is giving up and it is going to exit with an error.

As a first step, you may study the surrounding code and how that project code is organized, so that you may get more detailed ideas about how you may want to fix the issue (or some questions about parts that you don't get yet).

I do also suggest to take a look to [our CONTRIBUTING.md file](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md), which provides some hints about how to work on this project.

Feel free to ping me in a comment if you do have more questions or doubts that we can help you with.

**Comment by sonalprabhu** [comment]
Sure
Thank you

**Comment by sonalprabhu** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/35455325/94913387-cf20c880-04c6-11eb-89ae-d387e07718b0.png)
I am displaying it in this color in a loop. Is this fine?
