### ISSUE TITLE
Feature request: Add an API to return a list of android devices that web-ext detected

### ISSUE THREAD

**Issue by Jack-Works** [mozilla/web-ext#1999]
### Is this a feature request or a bug?

feature

### What is the expected or desired behavior?
https://github.com/DimensionDev/webpack-web-ext-plugin/blob/master/index.js#L26

Now we need to parse the text. It would be better to have an API for this so it's easier to build a better interface for it.

**Comment by rpl** [comment]
I guess that we may evaluate to export "src/utils/adb.js" to make it easier to reach the same utility methods that the firefox-android extension runner is using internally.

In the meantime you could achieve that by using the adbkit npm module that we are using internally and call its listDevices method directly: https://github.com/mozilla/web-ext/blob/180a5eb1c97803adef9458226fe86c3a46511c53/src/util/adb.js#L99

**Comment by ankushduacodes** [comment]
Hi @rpl, I would love to work on this. Please let me know if I may :)

**Comment by rpl** [comment]
> Hi @rpl, I would love to work on this. Please let me know if I may :)

@ankushduacodes Sure, it is not a critical issue but you can definitely work on it if it does look interesting for you.

The goal is to export the adb utilities we use internally (src/util/adb.js) to the third party nodejs scripts that are going to use web-ext as an npm dependency (instead of using it as a command line tool as usually).

You may want to start by trying to use web-ext as a library in a small nodejs script created by you, to experiment a bit with how that works. Some details about that are described in the README: https://github.com/mozilla/web-ext#using-web-ext-in-nodejs-code

Then you may also look to the test case we have to cover that and its related test fixtures (be aware that we only run that functional test when the environment variable CI is set, because as part of the test we have to call `npm link` and `npm unlink`, which affect the global npm packages and so we prefer to don't run it in the developers machines):
- https://github.com/mozilla/web-ext/blob/master/tests/functional/test.lib.imports.js

Some other caveats that may be useful once you start to look into the changes needed:

we try to avoid loading right away (while web-ext sources are being loaded) all the npm dependency that are only used for specific command or on specific options, e.g. if you look to [src/cmd/index.js](https://github.com/mozilla/web-ext/blob/master/src/cmd/index.js) you may notice that we have carefully exported functions that are loading the real command module lazily (which means that we do not load those modules until one of that functions is actually executed)

And so if we proceed with exporting from the web-ext npm package the helpers that the `src/utils/adb.js` module is exporting, we will want to do something similar to defer loading the npm dependencies that `src/utils/adb.js` is using internally.

There are some other details that are going to become more relevant once we are finalizing the needed changes, I'll point them out once we get there to avoid "putting too much stuff in the oven all at once" ;-))

Feel free to ping me if you have more questions or doubts (or if you got stuck and I can help you figure out how to proceed), I'll be likely a bit slower to reply in the following couple of weeks as I will be off for the festivities but I'll get to your comments as soon as I can ;-)

**Comment by ankushduacodes** [comment]
> The goal is to export the adb utilities we use internally (src/util/adb.js) to the third party nodejs scripts that are going to use web-ext as an npm dependency (instead of using it as a command line tool as usually).

> You may want to start by trying to use web-ext as a library in a small nodejs script created by you, to experiment a bit with how that works. Some details about that are described in the README: https://github.com/mozilla/web-ext#using-web-ext-in-nodejs-code

@rpl
1. If I understand it correctly, We want to register `adb.js` as an independent npm package and import it to the project as a `node_module`. 

   1. If so, then what happens to the relative imports? (for example: `import { isErrorWithCode, UsageError, WebExtError } from '../errors';`, Do we simply remove use of these errors and throw error in this way `throw new Error("something....")` ) 
   2. About these errors, Is it possible/Okay to import these errors from `web-ext` node_module to then use in the `adb.js` package. (Tried googling about this but could not find anything useful, almost all of the StackOverflow searches resulted in talking about how to handle node_module import errors.)
https://github.com/mozilla/web-ext/blob/180a5eb1c97803adef9458226fe86c3a46511c53/src/util/adb.js#L4-L8

   - I am asking these questions to because I am coming from python world where it is possible to import individual errors from the module on which our script depends upon.


2. Now I understand that I could be way off on what is being asked to do(wrt what I explained in point 1) and what I am understanding is to be done here, so here's my second understanding of what needs to be done here:
we keep the package as it is and simply export it to be used in this way: `webExt.utils.adb.ADBUtils` class.

**Doubt:**
I could not quite understand how is `webExt.util.logger`  is being exposed to the top-level object ie. the webExt of `const webExt = require('web-ext')`, Could you please help me understand this?

**Comment by rpl** [comment]
> @rpl Hi, Here are few of my conclusion and one doubt.

@ankushduacodes I confirm that the goal is not to split out `src/util/adb.js` into a separate nodejs package, but to just export it (or better "a subset of it", more on this later in this comment) from the web-ext npm package itself.

> Doubt:
> I could not quite understand how is webExt.util.logger is being exposed to the top-level object ie. the webExt of const webExt = require('web-ext'), Could you please help me understand this?

Sure thing. First of all we want to double-check what is exported by the web-ext npm package by looking in the package.json file:
https://github.com/mozilla/web-ext/blob/b3f590bd1cd9ac8a2de70b289bd7dac6645c89f0/package.json#L6-L9

As you can see in the snippet above, the web-ext package does export two kind of module formats (you may also take a look to https://github.com/mozilla/web-ext/pull/1934 to get some more context about why we do have two exports):

- `dist/web-ext.js` is the export in the NodeJS CommonJS format (using `require` and `exports`, which was the original module system more commonly used in nodejs so far, and still used while the migration to ESM is still in progress)

- `index.mjs` is the export in the ESM (EcmaScript Module) format (using `import` and `export`), which is basically just importing the CommonJS module and exporting it in a way that is nicer when importing it as an ESM module (which is why we introduced it in #1934)

`dist/web-ext.js` is created (using webpack) when you run `npm run build` in this repository, it is a bundle of all our sources from `./src/**.js` and `./src/main.js` is the entropoint exported by the generated `dist/web-ext.js` bundle.

The part of `./src/main.js` linked below is where we **re-export** `util.logger` (**re-export** as in "we import the `./util/logger` module bundled by webpack inside `dist/web-ext.js` and then re-export it from the commonjs module"):
https://github.com/mozilla/web-ext/blob/b3f590bd1cd9ac8a2de70b289bd7dac6645c89f0/src/main.js#L4-L10

Now, in one of the points above I did mention that it would be "better" to expose just a subset of the adb.js module, instead of exporting all of it as is (it was also one of the details I omitted in my previous comments to defer it to when we would be ready to discuss about that detail), and I would like to briefly explain you **why** and **how**.

About the **why**:
If we do export all the content of `./src/util/adb.js` as it is, then it is not going to be an **internal implementation detail** as it is at the moment, on the contrary it would become part of the **API we do expose from the package to external API consumers**. This means that we wouldn't be able to refactor it in a minor or patch release if we need to, because we may introduce a backward-incompatible change (which for the semantic versioning conventions should only happen as part of major releases). If we do expose a more limited API, we will more likely able to refactor it without introducing backward incompatible changes.

About the **how**:
we may define the small API we want to expose to external consumers either from `./src/util/adb.js` or from `./src/main.js` (if it turns out to require more than a few lines then I would stick to `./src/util/adb.js` to keep `./src/main.js` as small as possible).
The API we expose could be limited to just 2 methods and still cover the request described in this issue:
- `util.listADBDevices({adbBin: string}): Promise<Array<string>>`: this method gets an options object with just one optional string property `adbBin` (the path to the adb binary) and returns a Promise that resolves to an array of strings, which represents the adb devices
- `util.listADBFirefoxAPKs({adbBin: string}): Promise<Array<string>>`: same parameters of the previous one, but returns a Promise that resolves to an array of string that represents the apk packages identified as Firefox/GeckoView-based browser

Let me know if this details were useful or if you have more questions and doubts (technically I'm still away until next week but I'll try to get back to you sooner if I get a chance).
