### ISSUE TITLE
Option to choose target directory for temporal profile

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#2017]
### Is this a feature request or a bug?
Feature

### What is the current behavior?
Currently the new profile is being created in user "Temp" directory, on Windows it's "C:\Users\<user>\AppData\Local\Temp\<random UUID>".

### What is the expected or desired behavior?
I would like to be able to change this path to a different location.
**Why?**
Creating new profile takes on my PC between 12 - 25 seconds while my SSD has 100% utilization.
By having a fixed parent directory for my profile I would be able to exclude it from my antivirus scanner and even place it on a RAM disk.

Maybe I can already do this by using some environment variable? I couldn't find a switch in a docs though.

**Comment by Rob--W** [comment]
[`src/util/temp-dir.js`](https://github.com/mozilla/web-ext/blob/11faea68e20f38c22d3cb6308fbbb28ad7b4700f/src/util/temp-dir.js) is the primary location for generating temporary directories in `web-ext`. It [depends on the `tmp` module](https://github.com/mozilla/web-ext/blob/11faea68e20f38c22d3cb6308fbbb28ad7b4700f/src/util/temp-dir.js#L4), which in turn [allows the location to be configurable but otherwise falls back to `os.tmpdir()`](https://github.com/raszi/node-tmp/blob/7ae22ed2d56c10d425a66e99fe8bc10c925442e6/lib/tmp.js#L666).

`os.tmpdir()` is part of the Node.js core, and implemented here:
https://github.com/nodejs/node/blob/c1e672595f230d7e41ede5a96d778ada1c1e71ac/lib/os.js#L130-L148

From the code it should be obvious that you can use the `TEMP` or `TMP` environment variables to customize the location of the temporary directory.

```javascript
function tmpdir() {
  var path;
  if (isWindows) {
    path = process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
    if (path.length > 1 && path.endsWith('\\') && !path.endsWith(':\\'))
      path = path.slice(0, -1);
  } else {
    path = safeGetenv('TMPDIR') ||
           safeGetenv('TMP') ||
           safeGetenv('TEMP') ||
           '/tmp';
    if (path.length > 1 && path.endsWith('/'))
      path = path.slice(0, -1);
  }

  return path;
}
```

**Comment by Juraj-Masiar** [comment]
Thank you @Rob--W ! I like when people explain things thoroughly so that I learn something new :)

Anyway, this works great! By using small RAM disk I managed to reduce the profile creation to 3 seconds!
Maybe it would be worth to mention this in the docs? (about the target profile path, not the ramdisk)
