### ISSUE TITLE
Failing Tests: npm run test-functional on nodejs 14

### ISSUE THREAD

**Issue by tgiardina** [mozilla/web-ext#2050]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

I clone the repo, run `npm i`, and then run `npm run test-functional`. The following fails:

```
  web-ext run
    1) accepts: --no-reload --watch-file --source-dir SRCDIR --firefox FXPATH

```

The following tests are marked peding:

```
  web-ext imported as a library
    - can be imported as an ESM module
    - can be imported as a CommonJS module

```

### What is the expected or desired behavior?

Presumably these tests are supposed to pass.

### Version information (for bug reports)

* **Firefox version**: 81.0
* **Your OS and version**: Ubuntu 18.04.5 LTS
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v14.11.0
6.14.8
5.2.0

**Comment by rpl** [comment]
> ### Is this a feature request or a bug?
> 
> Bug
> ### What is the current behavior?
> 
> I clone the repo, run `npm i`, and then run `npm run test-functional`. The following fails:
> 
> ```
>   web-ext run
>     1) accepts: --no-reload --watch-file --source-dir SRCDIR --firefox FXPATH
> ```

This test is passing consistently on the CI, but we don't run the tests on nodejs 14 yet
I just tried locally and it does fail for me too.

The fix is actually only on the test side and pretty trivial, the issue is that in nodejs 14 the second parameter of `fs.writeFileSync` seems to be mandatory, but optional on nodejs <= 12.

I just created #2051 to fix the failure on nodejs 14 and also add nodejs 14 to the travis job matrix.

Thanks for filing an issue to let us know.  

> The following tests are marked peding:
> 
> ```
>   web-ext imported as a library
>     - can be imported as an ESM module
>     - can be imported as a CommonJS module
> ```

This test is skipped outside of the CI jobs on purpose, the reason is briefly described in the inline comment right above the `skip`:
https://github.com/mozilla/web-ext/blob/4ab30431ed717bea564d9e9a8abc4278d20b8121/tests/functional/test.lib.imports.js#L17-L22
