### ISSUE TITLE
Feature: Ability to hook into build process

### ISSUE THREAD

**Issue by daleharvey** [mozilla/web-ext#2055]
### Is this a feature request or a bug?

New feature

### What is the expected or desired behavior?

I am building an extension that has a rollup build process, once we started using rollup we need to have 2 shells open, one watching the source files change that triggers the rollup build (https://github.com/daleharvey/palmtree-result-extension/blob/master/package.json#L45) and another that has `web-ext run` to live reload the browser.

I would really prefer these to be run in the same process / command instead of 2 seperate shells (and without any complicated bashism), running web-ext from the command line doesnt help much as the main thing I need from web-ext is the reloading of the browser, it could be possible to configure some command that was invoked as part of web-ext's live reload process?

**Comment by Rob--W** [comment]
In relation to https://github.com/daleharvey/palmtree-result-extension/issues/6, you could use `npm run start & npm run watch` (or https://www.npmjs.com/package/concurrently) if you really want to. I don't think that you should be doing that, as the two are independent and can independently have useful output. One to build (and spit errors if a build error occur), and another one to run Firefox (and spit errors if the extension is syntactically invalid, or if the extension or browser could not be loaded/started for any reason).

> as the main thing I need from web-ext is the reloading of the browser, it could be possible to configure some command that was invoked as part of web-ext's live reload process?

I don't think that you're looking at the right place. The order should be rollup first, web-ext run second. There is no point in providing a hook before or after a "live reload" in web-ext, because that is too late. What you actually need is to reload the browser when the rollup process completes.

`web-ext` can be used as a library, as explained at https://github.com/mozilla/web-ext#using-web-ext-in-nodejs-code . If you are able to write a Node script that detects when rollup is done, then you can trigger a reload via the API from there.

**Comment by daleharvey** [comment]
I was thinking more along the lines of a pre build hook that build could call just before it reloaded the browser, but I was only thinking that because I hadnt seen that using `web-ext` as a library was able to do that (its right there in the example but I made a wrong assumption and skimmed it) so I have this workin with `extensionRunner.reloadAllExtensions()` now which is perfect. Cheers
