### ISSUE TITLE
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/%7Be5b2a2b6-5449-4540-9be4-6fc5924462a3%7D/versions/1.1/

### ISSUE THREAD

**Issue by Spl01ter** [mozilla/web-ext#2102]
status: 500
response: {"detail":"Internal Server Error"}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; font-src 'self' https://addons.cdn.mozilla.net; media-src https://videos.cdn.mozilla.net; default-src 'self'; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; object-src 'none'; base-uri 'self' https://addons.mozilla.org; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; form-action 'self' https://developer.mozilla.org; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; report-uri /__cspreport__","content-type":"application/json","date":"Tue, 22 Dec 2020 04:21:08 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Tue, 22 Dec 2020 04:21:23 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code","x-amo-request-id":"797dcd00aa824377912b7a9a78a58d86","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"34","connection":"Close"}

**Comment by rpl** [comment]
@ Spl01ter that errors seems to be related to an error that `web-ext sign` did got from the addons-server, it may be a transient issue but you are still able to trigger it consistently it would be better to it to https://github.com/mozilla/addons/issues along with some details about the extension you were submitting (just enough details to allow an engineer that works on the AMO server to investigate you issue).

I'm closing it as invalid this one because it is unlikely to be a web-ext issue (feel free to re-open it if after some investigation on the issue filed in https://github.com/mozilla/addons/issues does show that there is something that have to be fixed on the web-ext client).
