### ISSUE TITLE
Please consider using non-exact versions for your dependencies

### ISSUE THREAD

**Issue by julienw** [mozilla/web-ext#2112]
Hey,

I've noticed that in `package.json` all versions are defined exactly (without `^` as a prefix for example). The problem is that packages that depend on `web-ext` can't upgrade their transitive dependencies without web-ext doing it and releasing a new version. This is problematic for security problems, the latest being `node-notifier` (still not part of a released version).

The obvious solution is using the ^ prefix for all dependencies, at least the prod dependencies that are transitively pulled by dependents.

Thanks!

cc @rpl

**Comment by julienw** [comment]
Here is the warning in the dependabot alert in my repository:
![image](https://user-images.githubusercontent.com/454175/103906124-cb24c800-50ff-11eb-974c-c3b6b8084ebc.png)

**Comment by Rob--W** [comment]
We regularly update dependencies (provided that CI is green). I think that we'll continue to do that, we'll discuss this at the next triage meeting.

**Comment by julienw** [comment]
The downside of using non-exact dependencies is when a new version is breaking your code, and some users of your package installs for the first time or updates dependencies. This should be rare enough nowadays where people use a lockfile in addition to package.json (rare but possible).
This problem can also be minored with the `~` prefix (instead of `^`) which will accept only patch updates.

**Comment by rpl** [comment]
> The downside of using non-exact dependencies is when a new version is breaking your code, and some users of your package installs for the first time or updates dependencies. This should be rare enough nowadays where people use a lockfile in addition to package.json (rare but possible).
> This problem can also be minored with the `~` prefix (instead of `^`) which will accept only patch updates.

We experienced that kind of issue in this project (if I recall correctly one of the dependencies introduced an "apparently small change" in a patch release which was actually backward incompatible and it was breaking web-ext for the users that installed web-ext after that dependency was updated on npm).
It was pretty annoying to investigate that kind of bugs because of the mismatch between a freshly install and a previous one for the exact same package version.

As far as I remember the package-lock.json isn't meant to be published and it is not taken into account by npm install if it is not in the top level package in the current directory
If I'm not mistaken, a shinkwrap lock file should be generated from the package-lock.json file and published on npm as part of the package to make `npm install` to take into account the locked versions (see https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json and https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json).

We could look generating the shinkwrap file as part of the CI job and include it in the published package, if it would avoid the issue for the developers that are installing web-ext as a dependency instead of installing it globally (I think that as a first step we should double-check that the shrinkwrap lock file wouldn't trigger the same issue when installing web-ext as a dependency) but keeping the versions locked as it happens right now for the users that are installing it globally.

If that is the case, then we could update the github issue template to just ask for their project's package-lock.json file to the developers that will report issues related to web-ext installed as a dependencies (and assume that the version are the same as the shinkwrap lock file included in the package version if installed globally).

**Comment by julienw** [comment]
My mentioning of lockfiles was more about the fact that projects using your project will have their own lockfiles too for their users.

I believe in the past we could run into problems where _users_ of dependent projects could transitively install too recent dependencies. But nowadays that shouldn't be possible.
What is possible nowadays is a dependent project adding the web-ext dependency when some of the transitive dependencies are broken. While that's possible I think this is a rare event. Moreover we can expect the developer of this dependent project to test it at that moment, when they add the dependency (or update), so that wouldn't randomly break suddenly.

I wouldn't suggest using shrinkwrap which is a pre-lockfiles solution and IIRC has problems too.

**Comment by rpl** [comment]
@julienw from a quick look to the npm docs it doesn't seem that shrinkwrap has been deprecated, it looks that they kept it because it has a different role from the one that the package lock file does have (but I'm also concerned that it may just trigger the exact same issues of the exact versions and be pointless, and so we should take a deeper look to be sure of what will be the expected behaviors).

What I meant in my comment (and you also pointed out in your last comment) is that I'm pretty sure that if we will start using non exact dependencies then investigating issues reported by developers that install web-ext as a dependency would not be a problem because we can ask for their package lock file, but investigating issues reported by developers that installed it globally will likely be as annoying as it has been in the past.

Anyway we will discuss more about this in our next triage meeting and update this issue accordingly.

(And we may also release another minor or patch version next week once I'm officially back from PTO ;-), I think that I did already merge the `node-nodifier` patch release that should fix the more immediate issue with npm audit failures for the dependents packages).

**Comment by rpl** [comment]
@julienw in the meantime I did publish a new release ([5.5.0](https://github.com/mozilla/web-ext/releases/tag/5.5.0)), which includes the update of the node-notified dependency to v8.0.1, the new release should be published to npm by the CI job pretty soon.

**Comment by rpl** [comment]
We discussed about this during our triage meeting today and we agreed on closing this issue as wontfix.

We know first-hand why this may be annoying from time to time (e.g. [this repo does have a custom script to retrieve, parse and filter `npm audit` data](https://github.com/mozilla/web-ext/blob/master/scripts/audit-deps), similarly to how it was supported by the `nsp` cli tool that `npm audit` replaced, exactly because in some cases we had to ignore the ones that were not actually reproducible to avoid breaking arbitrary unrelated CI jobs), to reduce those issues we do update the dependencies regularly and we release ad-hoc minor or patch release when one of our dependency does have a security issue reported for.

**Comment by julienw** [comment]
Hey, I wanted to give another recent example: see this update https://github.com/julienw/webextension-build-script/pull/24/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de, where `semver` is duplicated because `addons-linter` depends on an exact version.

Here this applies to `addons-linter` and not `web-ext`, but that package suffers the same issue.

Do you think it would be possible to use `~` as prefix, so that only patch versions are accepted, which would probably avoid most of the problems you were seeing, but still allow some flexibility?

**Comment by rpl** [comment]
@julienw I was wondering: was any particular issue triggered by having two separate semver patch versions?

I'm not sure yet if this case does add anything that would make a convincing point to change our previous agreement of this topic, but I'm going to still add it as a discussion point for our next triage meeting (if we would decide to change the current approach related to the deps version pinning we should do it across all the packages that are composing web-ext and addons-linter and that we directly maintain, e.g. besides addons-linter and webext, there are also sign-addon and addon-scanner-utils that are all using exact version pinning).

**Comment by julienw** [comment]
Hey Luca, thanks for the answer!

No, there's no issue in this case, besides downloading the same package twice.

I'm still concerned that as a user of the package I can't control better the transitive dependencies, especially when the same dependencies are used by other packages. But that may be a necessary measure because of the other problems you mentioned earlier.

**Comment by fregante** [comment]
I don’t think this is effective. 

In package.json, you can control the exact version of 30 dependencies, but the remaining 441 dependencies are still free-updating. Any breaking patch update in **93% of the dependencies** will still break web-ext. When that inevitably happens, web-ext will still be powerless.

I know it's a pain to deal with involuntarily-breaking updates, but in practice this choice is just hostile to users and serves little purpose (again covering only 7% of the dependencies).

The only effective tool for this is the lockfile, which only the final user can use; if they don't use it, then it's their own problem.

**Comment by fregante** [comment]
> No, there's no issue in this case, besides downloading the same package twice.

Having multiple versions of the same package has several potential downsides, e.g. `x instanceof SomeClass` may be false if two versions of `SomeClass` have been installed.
