### ISSUE TITLE
"npm test" errors with dependency errors

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/web-ext#2214]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
If I build the current GIT state and after building run "npm test", then I get:

```
> web-ext@6.0.0 test
> node scripts/test

Running eslint...

/home/manuel/git/PKGBUILDs/web-ext-git/src/web-ext-git-build/web-ext-git/webpack.config.js
  4:23  error  'webpack' should be listed in the project's dependencies, not devDependencies                 import/no-extraneous-dependencies
  8:29  error  'webpack-node-externals' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

✖ 2 problems (2 errors, 0 warnings)
```

### What is the expected or desired behavior?
There should be no errors.

### Version information (for bug reports)

* **Firefox version**: 87
* **Your OS and version**: Arch
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v15.12.0
7.7.5
6.0.0

**Comment by rpl** [comment]
@M-Reimer we do run the npm test script in the CI jobs on each pull request, and we do use it during development as well, and in both cases I never got those errors (which are also quite unexpected, given that webpack.config.js is clearly something that should be part of the devDependencies).

I suspect that there is something related to how web-ext is being cloned and the npm test script executed which is preventing eslint from using the .eslintrc file from the web-ext repository, because eslint should be configured to allow those from this part of out .eslintrc file:
https://github.com/mozilla/web-ext/blob/8bd0d13f425bbaed6cfc2f8127883c5c43010f1d/.eslintrc#L162-L167 

Double-checking why eslint isn't picking up that config may allow you to figure out the issue you are experiencing.

From a web-ext perspective I think this is likely to be invalid (in other words "not a web-ext issue"), but I'll leave it open (marked as incomplete) for now, to give you a chance to look into what I described above and confirm as that there isn't anything to fix on the web-ext side as it seems.

**Comment by rpl** [comment]
@M-Reimer Closing as incomplete (but based on what I have seen while looking into this and described in https://github.com/mozilla/web-ext/issues/2214#issuecomment-818729926, this looks more likely invalid), but feel free to mention me in this issue if you got any new details that may require us to re-evaluate this issue.
