### ISSUE TITLE
Support creation of reproducible / deterministic extension ZIPs

### ISSUE THREAD

**Issue by Marcono1234** [mozilla/web-ext#2381]
### Is this a feature request or a bug?
Feature

### What is the current behavior?
The way the extension ZIP file is created by `web-ext build` is not reproducible or deterministic due to including the current timestamp. Possibly this is also affected by the ZIP entry order which might depend on the file system walk behavior of the operating system. This means that even if the source files of an extension are not changed, the binary data of the ZIP file differs.

This prevents calculating checksums to verify that an extension ZIP was indeed produced from its corresponding source code.
(Most likely this also makes it more difficult for you to review extensions submitted to addons.mozilla.org for signing.)

### What is the expected or desired behavior?
If possible, an option should be added to allow creation of reproducible extension ZIP files, ideally even across operating systems.
This should probably be opt-in because some users might prefer having the creation timestamp stored in their ZIP file.

Possibly useful:
- https://github.com/bitgenics/deterministic-zip
- https://github.com/archiverjs/node-archiver/issues/383

### Version information (for bug reports)

* **Firefox version**: _irrelevant_
* **Your OS and version**: Microsoft Windows [Version 10.0.19043.1586]
* Paste the output of these commands:

    ````
    node --version && npm --version && web-ext --version
    v16.14.0
    8.3.1
    6.7.0
    ````

**Comment by willdurand** [comment]
Hi, do you want to calculate checksums for XPIs submitted to AMO? (e.g., with the hope of getting the same checksum back after signing?)

**Comment by wagnerand** [comment]
For what it's worth, reviewers do not verify the checksum of the submitted XPI against a generated one. We compare the contents of both files.

**Comment by Marcono1234** [comment]
I just noticed this while locally building an own extension ZIP file, and thought this feature would be nice to have, to get some more confidence that a specific source code version really belongs to a ZIP file.

But feel free to close this issue if you don't think such a feature would be worth the effort.

**Comment by willdurand** [comment]
I think it is more about what use case you'd have rather than the effort it'd take us to update web-ext.

I asked about the expectations because AMO recreates XPIs when developers upload them and that would likely change the checksum calculated locally before signing. In addition, signed XPIs contain extra (signing) files, which would also change the checksum.

**Comment by Marcono1234** [comment]
Thanks a lot for the explanation! I wasn't aware of how AMO processes the XPI, and how the signing works exactly. For that use case having reproducible creation of ZIP files is probably not very useful at the moment then. Sorry for the hassle.

**Comment by l0b0** [comment]
Would it be possible to reopen this? Reproducible builds should be pretty easy:

- Set the file dates to a specific datetime, as in `touch -t 198001010000`.
- Use `umask` or `chmod` so that all files have the same access rights.
- Give the `zip` command a sorted list of input files rather than a directory to enforce the sequence. An easier option than [mine](https://gitlab.com/engmark/insecure-links-highlighter/-/blob/5880daaa3392256f0810e2f0ec0163572c0e435f/build.bash) would be to use `LC_COLLATE=POSIX`, `set -o globstar`, and then something like `files=("$source_dir"/**)` to list all files in `LC_COLLATE` order before passing them to `zip`.
