### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by laedit** [mozilla/web-ext#247]
It seems that some dependencies is missing, after installing web-ext I had to install:
 - any-promise
 - thenify-all
 - when
 - lodash
 - winreg

It is also visible when testing web-ext on [tonicdev](https://tonicdev.com/npm/web-ext).

**Comment by kumar303** [comment]
Was your npm up to date? There are known install issues with older versions.

**Comment by kumar303** [comment]
Better question: what was the exact npm version and node version you were using to install web-ext?

**Comment by laedit** [comment]
npm 2.11.3 and web-ext 1.0.1. I am running it on Windows 10.

**Comment by kumar303** [comment]
Ah, yes, that version of npm has known bugs in it -- it doesn't handle dependency flattening correctly. Thanks for the bug report but I'm closing this because there's nothing much we can do. Our [install instructions](https://github.com/mozilla/web-ext#installation-from-npm) already specify that you need to upgrade npm first.

**Comment by laedit** [comment]
Sorry for the issue, I haven't seen it.
