### ISSUE TITLE
Fire events

### ISSUE THREAD

**Issue by eviljeff** [mozilla/web-ext#2494]
I'd like to be able to use web-ext as a node dependency in a react website.  To be able to update the webpage mid-operation with status we need to fire some events that can be listened to (rather than just log to the console).

**Comment by rpl** [comment]
We discussed this issue during today's triage and we agreed to close this as wontfix, with the following motivations:

- if we would be implementing this in web-ext, we would be making the Client class to inherit from the nodejs EventEmitter (e.g. like the FirefoxRDPClient implemented in src/firefox/rdp-client.js), but EventEmitter wouldn't be available in the context of a webpage unless explicitly polyfilled (e.g. I think browserify used to do that, and I guess there may be also npm packages that can be manually introduced as dependency to polyfill nodejs EventEmitter), but there may be also better options if a similar module would be implemented by targeting the web specifically instead of both (node and web apps at the same time)

- we consider "using web-ext as a node dependency in code running inside a webapp" as out of scope for the web-ext npm package, in the medium and long run using web-ext as a dependency in the context of a webapp may become more of a technical debs for both the web-ext npm package and its consumer

The work being done for the submit-addon.js module integrated in web-ext itself it is still going to be helpful to inform the design of a similar module designed specifically with the webapps use case in mind (and initially the two may be basically the same), but we feel that (at least at the moment) keeping the two use cases separated will help to be free to pick up implementations strategy that fits better in the node and webapp use cases.
