### ISSUE TITLE
Feat: support `.web-ext-config.js` in the current directory.

### ISSUE THREAD

**Issue by uiolee** [mozilla/web-ext#2812]
### Feat 

>### Automatic discovery of configuration files
>
>web-ext will load existing configuration files in the following order:
>- A config file named `.web-ext-config.js` in your home directory
>- ......
>- A config file named `web-ext-config.js` in the current directory.

about Automatic discovery of configuration files, I hope that support `.web-ext-config.js` in the current directory, instead of  `web-ext-config.js`.

i dont undestand why the name of configuration files is different home dir and current dir. I don't think it's necessary

**Comment by Rob--W** [comment]
I don't understand the naming choice either; it was proposed in https://github.com/mozilla/web-ext/issues/730.

We can support another config file by adding it to https://github.com/mozilla/web-ext/blob/3ff64882d0e46c2952cbd661541981d68cc0a03f/src/config.js#L151C28-L158 , plus unit tests. For relevant files to touch, see the PR where the feature was originally introduced: https://github.com/mozilla/web-ext/pull/1161.

We should merge this change only at the next major version update, because the inclusion of a config file can potentially change the observed behavior. For example, a project could have a template `.web-ext-config.js` file with placeholders that someone should fill in.

**Comment by ioanarusiczki** [comment]
@willdurand Let me know if this requires qa and what to check.

**Comment by willdurand** [comment]
@ioanarusiczki yes please. This is about making sure that we can use a config file named `.web-ext-config.js`.

**Comment by ioanarusiczki** [comment]
@willdurand 

Inside add-ons folder I've added `.web-ext-config.js` (in my case empty) started an upload 
At the beginning of the upload I see the file is applied like `.\.web-ext-config.js`

I hope that's expected, a bit confusing because [here ](https://github.com/mozilla/web-ext/pull/2843#issue-1849764415) mentions a slash being used (not backslash)

![applying config file](https://github.com/mozilla/web-ext/assets/33448286/b96e0fd7-cf61-419f-95ca-93cfcedfd6c3)

**Comment by uiolee** [comment]
> the file is applied like `.\.web-ext-config.js`

`path.join()` will resolve the slash base on system, generally speaking we don't need to care about slashes.
