### ISSUE TITLE
Allow to download signed extensions

### ISSUE THREAD

**Issue by prometh07** [mozilla/web-ext#293]
I think it would be nice to have an option of downloading an already signed extension. It can be useful for certain development scenarios, especially when the final .xpi file is self-hosted from a server with the code in a different repository.

**Comment by kumar303** [comment]
I don't quite understand how you'd like to use this feature. Is this because when you run `web-ext sign` and your current version has already been signed you get an error like 'version already exists' ? Instead, would you like to re-download the signed file?

**Comment by prometh07** [comment]
Exactly.

**Comment by kumar303** [comment]
I think this would be too hard to get right because even though the version number is the same, the contents of the old package may not be the same. In other words, you could change some code and forget to increment the version number so mozilla's API would give you the wrong file. The signing API does not offer a way to check a digest hash of the original package that was used for signing. I think the best thing is to manage the files yourself.

**Comment by kumar303** [comment]
Because this would be hard to implement (I think), I'm closing this since there is an easy workaround. The workaround is to manage your own files as you get them signed. If someone can provide a compelling case that makes the workaround difficult then we could revisit this issue.

Thanks for reporting the issue!

**Comment by tombh** [comment]
Just a potential use case to add to the mix:

I build my extension on Travis CI, so I don't have local access to the XPI. Now I've hit a bug with one of my releases and I can't seem to download the XPI from my addons.mozilla.org developers account. Firefox keeps saying: "the addon could not be downloaded because of a connection failure". So what can I do, there doesn't seem to be any way to actually get at my XPI in order to debug it :/
