### ISSUE TITLE
Guru Nanak Workshop Services Pvt Ltd

### ISSUE THREAD

**Issue by hrgeckota** [mozilla/web-ext#3290]
### Version information (for bug reports)

- **Firefox version**:
- **Your OS and version**:
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
```

**Comment by hrgeckota** [comment]
![123](https://github.com/user-attachments/assets/5294ba57-9976-44ad-8c83-4cc5a22a6801)

**Comment by Rob--W** [comment]
The error message seems to originate from Chrome and is self-explanatory: the manifest.json file of your extension specifies the "persistent" keyword in its "background" section, which is not supported in Manifest Version 3. Unlike Firefox and Safari, Chrome does not support event pages any more, only the new "service_worker" key.

For more information, see https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers

I am closing this issue since it is not a problem with the web-ext tool.
