### ISSUE TITLE
Move --source-dir coercion into its option configuration

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#438]
The `--source-dir` path needs to get coerced into a resolved path. We had a hack in place to do this while we waited on https://github.com/yargs/yargs/issues/535. Let's remove the hack!

The old way was to [coerce the value](https://github.com/mozilla/web-ext/blob/master/src/program.js#L82-L86) in `run()`.

The new way can be to use the [.coerce()](https://github.com/yargs/yargs#coercekey-fn) callback. We upgraded yargs for this feature in https://github.com/mozilla/web-ext/pull/435

**Comment by shubheksha** [comment]
For this, I figured that I'll need to make changes [here](https://github.com/mozilla/web-ext/blob/master/src/program.js#L153). However, on going through the [docs](https://github.com/yargs/yargs#coercekey-fn), it isn't very clear how it'll be implemented as opposed to the way alternate usage options have been given for [choices](https://github.com/yargs/yargs#choiceskey-choices).

**Comment by rpl** [comment]
> @rpl, can you give me some direction on this issue? 
@shubheksha sure, it seems that this new yargs `coerce` feature can be used to transform a value passed to a yargs option, to be able to try this change we need to:

- remove the old code that is currently handling this transformation: https://github.com/mozilla/web-ext/blob/master/src/program.js#L82-L86

- define a `coerce` function for the sourceDir option, using one of the supported syntax, e.g.

Defined as a property of the `option` config object:

```
program.setGlobalOptions({
    'source-dir': {
      alias: 's',
      ...
      type: 'string',
      coerce: (value) => {
         let newvalue = ....;
         ...;
         return newvalue;
      }
},
```

or using the coerce method: 

```
...
program.yargs.coerce('sourceDir', (value) => { ... });
...
```

For this PR we just need to transform the value using `path.resolve`, and so our `coerce` definition is probably even simpler of the above snippets.

**Comment by shubheksha** [comment]
@rpl, thanks, got it! I was wondering if the syntax in the first snippet was valid or no even though it made sense in my head -- this cleared it up. I'll open a PR with the required changes soon.

**Comment by shubheksha** [comment]
@rpl, I made all the required changes & everything works fine except for test which fails repeatedly & I am not being able to figure out why. [This](https://github.com/mozilla/web-ext/blob/master/tests/test.program.js#L280) line isn't giving the required output. I've attached the screenshot for reference. 
![image](https://cloud.githubusercontent.com/assets/7693422/17865362/ddcd41b2-68bf-11e6-83c1-1e167d3376fe.png)
Why is the path being resolved to just `..` & not what's required?

**Comment by rpl** [comment]
@shubheksha I took a look and the following is the reason of the above failure:
currently the conversion of the `sourceDir` path into an absolute dir is done in the `run` method of the `Program` class, but with the change that you are preparing the conversion will be done in the `main` function exported from the same source file (which then calls `program.run` as its last step: https://github.com/mozilla/web-ext/blob/master/src/program.js#L279), and so we need to rewrite that test case as a test of `main` instead of `run` (and move the test in the right group: https://github.com/mozilla/web-ext/blob/master/tests/test.program.js#L232).

**Comment by wagnerand** [comment]
Removing 'maybe good first bug' since someone is already working on it.

**Comment by shubheksha** [comment]
@rpl, I am confused about what you said regarding the modification of the test. From what I understood, currently, the test resides in the `program.main` group, which according to what you said is it's rightful place since the test belongs to the `main` function itself. The test calls the [main](https://github.com/mozilla/web-ext/blob/master/tests/test.program.js#L236) method of the `program.js` which in turn calls [program.run](https://github.com/mozilla/web-ext/blob/master/src/program.js#L279). Am I missing something here?

**Comment by rpl** [comment]
@shubheksha my apologies, I think that you are right, initially I've been tricked by our mocks in this pretty long test file, but I tried to make the above change and the coerce function is definitely called, nevertheless the `argv.sourceDir` doesn't seem to be affected by the change.

I'm going to try `coerce` in a smaller nodejs script to check if it's an issue related to how we are using yargs.

**Comment by shubheksha** [comment]
@rpl, alright! :) I had a question - how did you test whether coerce function is being called or not? I wanted to step through the code as well to see what's happening, but I was clueless how to do it. I've debugged JS in the browser, but is there a tool which I can use to debug JS outside of it too?

**Comment by rpl** [comment]
@shubheksha that is a very good question, there are different debugging strategies that can be used to debug a nodejs application and check if it is executing (and who is calling it) a particular part of our application:

- the simplest is adding some logging (temporarily) to be able to visualize how the data is flowing in our application based on this "tracing" logs (this seems a very crude debugging strategies, but with asynchronous code is sometimes the best and fastest option)

- the more complete way to debug it properly is running the application in debugging mode, maybe adding some `debugger` statement where we want to be sure that the debugger will pause.

e.g. we can apply the following temporary changes (something that will not be part of the final patch):
```
diff --git a/src/program.js b/src/program.js
index 8cda452..09b7c1b 100644
--- a/src/program.js
+++ b/src/program.js
@@ -79,6 +79,7 @@ export class Program {
         this.yargs.exitProcess(this.shouldExitProgram);
         argv = this.yargs.argv;

+        debugger; // <= This will stop the debugger where the sourceDir value is 
+                         //       supposed to be already resolved
         // Fix up sourceDir. This can hopefully move to option configuration
         // soon. See https://github.com/yargs/yargs/issues/535
         if (argv.sourceDir) {
@@ -157,6 +158,10 @@ Example: $0 --help run.
       normalize: true,
       requiresArg: true,
       type: 'string',
+      coerce: (value) => {
+        debugger; // <= This will pause the debugger every time this function is executed 
+        return path.resolve(value);
+      }
     },
     'artifacts-dir': {
       alias: 'a',
```

Once we made the above changes we can run the single test that we are interesting in (which will reduce the amount of noise that we need to filter out to focus on the issue we want to debug) with the debug repl enabled:

```
$ ./node_modules/.bin/mocha debug -r babel-core/register tests/test.program.js -f "sourceDir"   
```

This command is composed of:
- `./node_modules/.bin/mocha` is the test runner executable
- `debug` is a mocha command which run the tests with the debugging repl enabled
- `-r babel-core/register` is a mocha option, needed to transpile es6 into es5 on the fly
- `tests/test.program.js` is the test file that we want to run
- `-f "sourceDir"` is a mocha option which filter the tests and execute only the ones that match the string

Once we run the above command we get the debugger prompt and the nodejs application paused on the mocha sources:
```
< Debugger listening on port 5858
connecting to 127.0.0.1:5858 ... ok
break in node_modules/mocha/bin/_mocha:7
  5  */
  6
> 7 var program = require('commander'),
  8   path = require('path'),
  9   fs = require('fs'),
debug>
```

Using the repl command "c" (and pressing return), we will continue the execution until the this `debugger` statement has been reached:

```
debug> c
<   program.main
break in src/program.js:197
 195       type: 'string',
 196       coerce: function coerce(value) {
>197         debugger;
 198         return _path2.default.resolve(value);
 199       }
debug> repl
Press Ctrl + C to leave debug repl
> console.log(value, "=>", _path2.default.resolve(value))
< .. => /zfs-mordor/work/webext/tools
>
``` 

Now that we are in our `coerce` function (the version transpiled from es6 to es5 to be honest), we can use the "repl" command to get a regular nodejs repl that is executing code in the context of the above paused execution.

Or for the simpler approach we can add a temporary `console.log` where we put the `debugger` statement in the above examples, execute the test and look and the output of the tracing in the console.

PS: another debugging trick that is useful to know is how to use an Error instance to get the current stack and print it into the tracing log, e.g. something like:
```
      coerce: (value) => {
        console.log("CANARY", {value, coerced: path.resolve.value, calledFrom: Error().stack});
        return path.resolve(value);
      }
```

**Comment by rpl** [comment]
@shubheksha I've been able to isolate the source of the issue, it was way simpler that it seems but it wasn't so easy to debug and spot :-D

as an initial hint:
one of the other properties that we are using in the `sourceDir` option definition doesn't play well with the `coerce` function, and after removing that single property the coerce function finally works as expected and sourceDir is resolved as expected.

PS: I'm giving you only the initial hint, so that you can experiment a bit with the nodejs debugging techniques, but let me know if you need more hints about this issue, there is no need to turn it into a frustrating experience, software is written together and it is ok to solve some issues in pairing ;-)

**Comment by shubheksha** [comment]
@rpl, thank you so much for such a detailed & informative reply! I had no idea this could be done. And I really appreciate the fact that you didn't tell me the solution right away. I really want to try & figure things out on my own as I learn the most that way. :)
I was trying to use the debug option, but I can't reach the breakpoint using the "c" command as you mentioned above, instead this happens:
![image](https://cloud.githubusercontent.com/assets/7693422/17942898/f35781f8-6a56-11e6-8ae2-d059a32f1212.png)

**Comment by shubheksha** [comment]
So I managed to figure out that the conflicting property was `normalize`, but I don't really understand why.  Could you please elaborate on that? I'd still like to know why I couldn't run the tests & step through the code to see what's happening.

**Comment by rpl** [comment]
The reason for the conflict with normalize is definitely inside `yargs-parser` (and I filed as issue as yargs/yargs-parser#56 with attached a minimal nodejs example that reproduce the issue)

I'm unable to reproduce locally your issue with `mocha debug`, it seems that for some reason node it is not able to run the result of the babel transpiling of the ES6 code into ES5 code, but I'm unable to reproduce it even by running it on nodejs-4.4.4 (the same version in the screenshot above).

Can you try to remove the `node_modules` dir and run `npm install` again to recreate it?

**Comment by shubheksha** [comment]
That fixed it! I was able to step through the functions & peep inside them! Thank you so much for introducing me to this -- I had no idea it exists! 
Also, how did you figure out that `normalize` is conflicting? Even stepping through the calls didn't make it obvious that it's overriding the `coerce` function.

**Comment by rpl** [comment]
@shubheksha sorry for the late reply (I was off for a day).

> That fixed it! I was able to step through the functions & peep inside them! Thank you so much for introducing me to this -- I had no idea it exists!

I'm so glad to hear that! Welcome in the nodejs debugging! ;-)

> Also, how did you figure out that normalize is conflicting? Even stepping through the calls didn't make it obvious that it's overriding the coerce function.

To detect which part of the code is introducing an issue I usually start by "building an immaginary fence" around the issue, and then checking that the issue is actually still "inside the fence" (e.g. starting from: is this code actually executed?)

then I "build" a smaller "imaginary fence" inside the previous one (e.g. what can I exclude from the potential causes of this issue? which part of our code is important for the issue?), and iterate this process until, finally, I got an "imaginary fence" that is so small that it only contains the issue :-)

In particular, in this case:

- using the debugger I wanted to be sure that the code that we expected to have been executed is actually called by the test case which fails (e.g. the `coerce` function has been executed), and to print, from the node debugging repl using a `console.log`, the value of `sourceDir` where I expect it to be the result of `path.resolve` (and by doing this I noticed that `sourceDir` sometimes is printed as a getter/setter instead of a simple property with a string value assigned).

- then I started to ask myself: what are the other properties near the `coerce` function that could likely be related to the issue? what I would extract if I want to reproduce the issue with a smaller amount of code?

At this point `normalize` suddenly became the best candidate, because it was the only other option in that group that was related to 'paths" post-processing, and could likely be the source of the `coerce` issue.

With the growing in experience you become able to execute most of this steps without even noticing (and even without touching your keyboard), just by reproducing the behavior in your mind based on the previous knowledge / experience with the components that you are working on.

**Comment by shubheksha** [comment]
Thank you so much for this detailed explanation. It makes so much more sense now rather than an obscure magic trick! Everything I learnt by solving this issues, i.e., debugging, isolating & issue, etc., is going to be super useful in the future! 
Instead of following all the steps you outlined, I directly jumped to the conclusion that since `normalize` is the only property directly related to paths, it might be the one causing the issue.

Next step will be to update the documentation for `firefox-binary`, but that'll be done after this PR is merged, right?

**Comment by rpl** [comment]
> Thank you so much for this detailed explanation. It makes so much more sense now rather than an obscure magic trick! Everything I learnt by solving this issues, i.e., debugging, isolating & issue, etc., is going to be super useful in the future!

@shubheksha hehehe, that's true! there is no obscure magic trick ;-)
it is just a matter of following the data flowing into our application and find where the things goes differently from what we thought :-D

> Next step will be to update the documentation for firefox-binary, but that'll be done after this PR is merged, right?

Yep, we need to document it and we need to decide how to release the change (e.g. if we completely remove the old option then we need to release it as a new major version incompatible with the previous one, or if we prefer to translate the old option into the new one and release it as a new minor/patch version, as described by the semantic versioning conventions: http://semver.org/).

**Comment by kumar303** [comment]
fixes in https://github.com/mozilla/web-ext/pull/453
