### ISSUE TITLE
Contributors should squash commits before raising PR

### ISSUE THREAD

**Issue by karuppiah7890** [mozilla/web-ext#553]
### Is this a bug or feature request?

Request to include an extra guideline in the "contribution guidelines".

### What is the current behavior?

Currently contributors can raise PRs that have more than one commit. 

(If this is a bug, please include the exact steps to reproduce the problem, including the
`web-ext` commands you ran. Do not include sensitive information like API secrets.
Upload a text log created with the `--verbose` flag if possible.
Upload a .zip file of your web extension source if necessary.)

### What is the expected or desired behavior?

I have seen many repositories requesting contributors to follow conventions like squashing many commits into one, before raising a PR. And they reason this out by saying that it keeps the repository more sane.

I think even web-ext should follow this. @kumar303 Your comments ? 

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`:
* Output of `node --version`:
* Output of `npm --version`:
* Firefox version:
* Your OS and version:

**Comment by kumar303** [comment]
Hi. We did have a section in the [contributor guide](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md) about his.

However, you reminded me that we don't need it so I [removed that section](https://github.com/mozilla/web-ext/commit/508db12536157bdab35959a84329e16c309c324e). It's no longer necessary for contributors to squash commits because we can do it automatically [when we merge now](https://github.com/blog/2141-squash-your-commits). This makes contributing to web-ext a lot easier!

**Comment by karuppiah7890** [comment]
Oh yes. I actually noticed the squashing section only later. But then, however I noticed that there were multiple commit PRs. That's why I didn't remove the issue. But now I see that you use automatic squash and merge. Cool!
