### ISSUE TITLE
Launch browser at specified page

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#647]
### Is this a bug or feature request?
Feature

### What is the current behavior?
When you run it starts Firefox with a blank page.

### What is the expected or desired behavior?
Would be awesome if I could define a URL at the command line to open. It could be a page that runs automated tests or just a page that allows me to manually click a few things.

**Comment by saintsebastian** [comment]
@kumar303 @rpl I'd like to work on this

**Comment by rpl** [comment]
@saintsebastian sure! let me know if more context is needed to make this actionable!

**Comment by gregglind** [comment]
my proposal would be a `--url` argument that can be given multiple times, as opposed to a comma separated list.

**Comment by rpl** [comment]
@gregglind :+1: @saintsebastian is working on it on #709 (and it is almost done).

The cli option is going to be called `--start-url`, but (besides the name) it is going to work exactly like you described above (it can be passed multiple times and it is going to open the specified urls into multiple tabs)

**Comment by gregglind** [comment]
1.  Awesome.
2.  Nit:  cli options with internal hyphens... could that just be url?
 (Usual json / python objects with keys with hyphens are annoying.
3.  Would it be worth having a list of all proposed cli stuff somewhere so
it stays coherent?
4.  Ps, I LOVE cli design.

**Comment by rpl** [comment]
@gregglind I would not be strongly against rename it `--url`, the reason why I suggested to name this cli option as `--open-url` or `--start-url` is mostly related to how yargs converts the cli options into javascript properties, because we pass these identifiers around in the web-ext internals and `openUrl`/`startUrl` was more explicit (than `url`) about what the identifier content represents.

Unfortunately it is probably too late to change the general convention on the web-ext cli options, because we have already a number of existent cli options with internal hypens, e.g. `--artifact-dir`, `--source-dir`, `--firefox-profile`, `--no-reload`.

But we can still provide a nicer "single letter alias" for this new cli option, e.g. 
`-u` is currently available

how it sounds to you?

About a list of proposed cli stuff, I agree: keep the cli options consistent is something that we deeply care about and we constantly keep an eye on (we spend so much time on the cli that every small detail matters :-P)

we are currently discussing and enforcing the consistency during/through the code reviews, but I totally agree that we can make it more explicit and keep the convention and the discussions/decisions related to next options planned in a more visible shared place than the single issue/pull request.

My proposal:

- add a new section related to the "cli option naming conventions" into the CONTRIBUTING.md file
- create a list of the existent and the proposed cli options in a single place (e.g. a "tracking" github issue or a github wiki page? the wiki is currently disabled on this repo, but we can enable it if it can be helpful)

@kumar how it sounds to you?

**Comment by gregglind** [comment]
All of that sounds pretty amazing :)  I am totally satisfied that you have
it UNDER CONTROL.

**Comment by kumar303** [comment]
This landed in https://github.com/mozilla/web-ext/pull/709 , thanks @saintsebastian !

**Comment by andymckay** [comment]
Woot, thanks @saintsebastian.

**Comment by kumar303** [comment]
Thanks again for this @saintsebastian ! I just pushed out the release. If you have some time, could you document the new `--start-url` option on the [run command reference page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) ?

**Comment by saintsebastian** [comment]
@kumar303 I tried my hand, please let me know if anything needs to be added or edited.

**Comment by kumar303** [comment]
@saintsebastian thanks! The docs look good
