### ISSUE TITLE
How to install web-ext on Ubuntu ?

### ISSUE THREAD

**Issue by WarGot-by** [mozilla/web-ext#673]
Good day. After write command npm install --global web-ext I get an error
npm WARN optional Skipping failed optional dependency /web-ext/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

How to fix this error or exclude fsevents from the dependencies
➜npm -v  = 3.8.6
➜nodejs -v 5.12.0
➜cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
➜uname -v
#49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016

**Comment by rpl** [comment]
@WarGot-by The warning is related to a dependency of [chokidar][chokidar], which is the actual direct dependency of web-ext that optionally uses the [fsevents][fsevents] npm package  (`chokidar` is an nodejs cross-compatible library to watch for changes, `fsevents` is optionally used to make it more performant of OSX), but that warning message should not affect the ability of web-ext to work correctly (and full featured) on Linux.

Are you experiencing any issues on your system?

(I use Linux as my main OS on my laptop, Ubuntu 16.04 to be precise, and the same warning is logged for me too, but nevertheless web-ext works correctly on my system, because chokidar fallbacks on what is supported on Linux).

[chokidar]: https://github.com/paulmillr/chokidar
[fsevents]: https://github.com/strongloop/fsevents

**Comment by WarGot-by** [comment]
@rpl Hi. Thanks for answer. After error web-ext not install in system -(

➜  test git:(master) ✗ npm install --global web-ext 
➜  test git:(master) ✗ web-ext run
zsh: command not found: web-ext
➜  test git:(master) ✗ web-ext --help
zsh: command not found: web-ext

**Comment by kumar303** [comment]
Hi @WarGot-by , thanks for the additional details. It looks like it installed successfully, you just don't have the `web-ext` [executable on your $PATH](http://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh). Try running this to find out what path you need to add:

     npm config get prefix

For me, it says:

    /Users/kumar/.nvm/versions/node/v6.3.0

So I would [add this to my $PATH](http://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh):

    /Users/kumar/.nvm/versions/node/v6.3.0/bin

Because that contains the executable:

    /Users/kumar/.nvm/versions/node/v6.3.0/bin/web-ext

**Comment by WarGot-by** [comment]
@kumar303 Good afternoon. Thanks for the your tips. I install npm web-ext without -- global to project directory, and added PATH. All works. Thanks.

**Comment by WarGot-by** [comment]
@kumar303 @rpl Thanks for the help. Everything worked. I close the issue.
