### ISSUE TITLE
Configure the Program class to use config parsing helpers

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#775]
This is a stepping stone toward implementing all of #176

After landing the config helper objects in https://github.com/mozilla/web-ext/pull/744, let's hook them up to the Program class so that you can get config handling working on the command line.

**Comment by saintsebastian** [comment]
@kumar303 @rpl I think since @shubheksha is busy I can take over some of config issues. I assume this one is the easiest entrance to the work done already.
As far as I understand here is what needs to be done:
1. add global option `--config=/path/to/web-ext-config.json` (is it fully global or should be blocked on some commands?)
2. commands own options will override global config option
3. use `config.js` helper function `applyConfigToArgv` to apply changes.

So far it seems to be mostly just connecting dots made by @shubheksha. Let me know if I am missing somethign and whether it's ok to take over this issues

**Comment by kumar303** [comment]
This is now documented:
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Using_a_configuration_file_for_option_defaults
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--config_-c
