### ISSUE TITLE
web-ext build shouldn't say "Your web extension is ready" if manifest.json doesn't have applications.gecko.id key

### ISSUE THREAD

**Issue by arai-a** [mozilla/web-ext#847]
related to https://bugzilla.mozilla.org/show_bug.cgi?id=1344674

### Is this a bug or feature request?

a kind of UX bug

### What is the current behavior?

Steps:
1. create `test` directory
2. enter `test` directory
3. create `manifest.json` with the following content
```
{
  "manifest_version": 2,
  "name": "test",
  "version": "1.0",
  "description": "test"
}
```
4. run `web-ext build`
5. open Nightly 55.0a1 (2017-03-08) (64-bit)
6. open about:addons
7. drag and drop generated .zip file onto "Extensions" pane

Result:

`web-ext build` prints the following message:
```
Building web extension from /tmp/test
Your web extension is ready: /tmp/test/web-ext-artifacts/test-1.0.zip
```

and then Firefox says:
```
undefined
This add-on couldn't be installed because it appears to be corrupt.
```

### What is the expected or desired behavior?

`web-ext build` shouldn't say "Your web extension is ready" for this case.

Firefox is complaining the add-on is corrupt because `manifest.json` doesn't have `applications.gecko.id` key.

It's hard to figure out why Firefox is saying it's corrupt, because there's no issue while debugging with temporary add-on, and `applications.gecko.id` doesn't exist in almost all examples.

`web-ext build` should check the existence of `applications.gecko.id` key before saying "Your web extension is ready",
and if there's no `applications.gecko.id` key, it should suggest adding it, or just say "Your web extension is ready for submitting to addons.mozilla.org",
to prevent developers from trying to install the zip to Firefox and bumps into the unhelpful error message.

### Version information (for bug reports)

revision c3ff1c3ee7eb81aaf62522b00e0e7a310bfec02a

* **Firefox version**: 55.0a1 (2017-03-08) (64-bit)
* **Your OS and version**: macOS Sierra 10.12.3
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

```
v7.5.0
4.1.2
master-c3ff1c3ee7eb81aaf62522b00e0e7a310bfec02a
```

**Comment by rpl** [comment]
@arai-a Thanks for reporting this, I totally agree that the error message "This add-on couldn't be installed because it appears to be corrupt." is not very helpful, and that combined with the message ("Your web extension is ready") that is currently logged by "web-ext build", it can be even more confusing.

Changing the message logged by web-ext sounds right to me, but in my opinion it shouldn't push the addon developer to put an explicit id in the applications.gecko.id (which should only be necessary for addons that are migrating from the legacy Firefox addon technologies to a WebExtension, and when the addon developer wants to test the storage.sync feature), and it will not be enough on a stable version of Firefox, where the signature is mandatory if the addon is not installed as a "temporarily installed addon".

on the contrary I would be completely ok if the message would be changed into something like:
```
Your web extension is ready for being submitted on addons.mozilla.org:
```

especially given that:
- it is simpler to run the addon locally using "web-ext run", that doesn't require an explicit id to be assigned in the manifest
- the main use case of "web-ext build" is definitely "submitting the addon on addons.mozilla.org", so that it can be reviewed and listed (because if you don't want the addon to be listed on AMO, you can more immediately get the signed xpi using "web-ext sign", and the resulting signed xpi has an extension id assigned through the signature and it can be successfully installed from the "about:addons" page, as well as from "about:debugging#addons").

**Comment by arai-a** [comment]
Okay, thanks :)
I'll fix my PR.

**Comment by kumar303** [comment]
Hi, thanks for the detailed bug report! I gave some [feedback](https://github.com/mozilla/web-ext/pull/849#discussion_r105016502) on your proposed patch but I also wanted to mention that the bug you see in Firefox is [tracked here](https://bugzilla.mozilla.org/show_bug.cgi?id=1224591). In summary, it's a terrible error message but the module owners are not convinced it should be fixed. I think it would be nice to fix. I'm not really sure that web-ext should try to work around it though.

**Comment by kumar303** [comment]
Also, here are some responses 

> Firefox is complaining the add-on is corrupt because manifest.json doesn't have applications.gecko.id key.

Are you sure? I think it might be complaining that the add-on is not signed. Did you try it with `xpinstall.signatures.required = false` ?

> applications.gecko.id doesn't exist in almost all examples.

This is by design because adding an ID makes the extension incompatible with Chrome.

> open about:addons... drag and drop generated .zip file onto "Extensions" pane

Why are you doing it like this? Are you trying to install your add-on permanently to use it? If you are just trying to test it for development, [loading it as a temporary add-on](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) is the expected approach. 

Loading a `.zip` in about:addons is hard to get working because you have to disable signature checking or sign the add-on first.

**Comment by andymckay** [comment]
Please note: we are also planning large and detailed messages in about:debugging too, linking to MDN to let people know whats going on.

**Comment by arai-a** [comment]
> >  Firefox is complaining the add-on is corrupt because manifest.json doesn't have applications.gecko.id key.
> 
> Are you sure? I think it might be complaining that the add-on is not signed. Did you try it with xpinstall.signatures.required = false ?

Sorry my comment wasn't clear about the reason.
yes, I set xpinstall.signatures.required to false.

the reason why it's complaining is that (from my understanding from the code):
  1. the add-on doesn't have an id
  2. it's not signed (that the system generates an id from cert name)
  3. it's not temporary installation (that the system generates a temporary id)

https://dxr.mozilla.org/mozilla-central/rev/58753259bfeb3b818eac7870871b0aae1f8de64a/toolkit/mozapps/extensions/internal/XPIProvider.jsm#1562-1572

and currently Firefox is complaining the id is not found, in browser console.
https://dxr.mozilla.org/mozilla-central/rev/58753259bfeb3b818eac7870871b0aae1f8de64a/toolkit/mozapps/extensions/internal/XPIProvider.jsm#5570-5573
(I don't think the message is discoverable tho)


> > applications.gecko.id doesn't exist in almost all examples.
> 
> This is by design because adding an ID makes the extension incompatible with Chrome.

okay, so, the Firefox's error message ("Cannot find id for addon") is saying totally wrong thing, and it should show the error message that "add-on is not signed", right?


> > open about:addons... drag and drop generated .zip file onto "Extensions" pane
> 
> Why are you doing it like this? Are you trying to install your add-on permanently to use it? If you are just trying to test it for development, loading it as a temporary add-on is the expected approach.

I'm trying to install it permanently, after finished debugging with temporary add-on.

That makes the situation even worse, since there was no issue while debugging with temporary add-on.  there's no difference between them except whether it's zipped or not, and hard to come up with the reason why it fails, without looking into the Firefox's code, and I don't think it's desirable.


> Loading a .zip in about:addons is hard to get working because you have to disable signature checking or sign the add-on first.

Yes, I've already disabled it.
I'm trying to port my private extensions to webextensions.
as long as it works without signature, it's better avoid sending it outside.

**Comment by kumar303** [comment]
> I'm trying to install it permanently, after finished debugging with temporary add-on.

Ah, ok. The `sign` command is intended for this. Were you trying to avoid that since the source code is private? In that case, using `build` would be expected but, yeah, the Firefox errors are not great. You're right, it looks like signing is not the issue in your case. It is probably just a variation of [bug 1224591](https://bugzilla.mozilla.org/show_bug.cgi?id=1224591). Not being able to install an add-on without an ID when signing is disabled is definitely a bug.

**Comment by arai-a** [comment]
> Were you trying to avoid that since the source code is private?

Yes.
Actually, the one that I was trying doesn't contains so much private data at that point, since it's my first WebExtensions that implements very small part of existing bootstrap extension.
but I don't see any reason to send it to other server for signing (no reason to expose the data, no reason to consume traffic nor server storage, etc).
also I'll add more private things later.


> Not being able to install an add-on without an ID when signing is disabled is definitely a bug.

I see.
I'll look for a bug for it.

**Comment by arai-a** [comment]
> Please note: we are also planning large and detailed messages in about:debugging too, linking to MDN to let people know whats going on.

is there already a bug filed?

**Comment by arai-a** [comment]
> > Not being able to install an add-on without an ID when signing is disabled is definitely a bug.
> 
> I see.
> I'll look for a bug for it.

Unfortunately, they're not going to fix this issue :/
(they don't think this is a bug...

**Comment by arai-a** [comment]
I don't see any hope on fixing this issue on Firefox's side.

**Comment by kumar303** [comment]
That's unfortunate that they are not open to fixing this on the Firefox side. It is a bit of an edge case but still seems like a bug to me.

**Comment by Utopiah** [comment]
2025 and still relevant sadly. I found this issue precisely because after using `web-ext run` and everything worked well I tried to install the extension on my phone, to use it on the go. I thus tried `web-ext build` which did appear to succeed. I then uploaded the file to my phone, went to dev mode, tried to install the new `.zip` file... only to be greeted with an error message that gave no indication about signature required.
