### ISSUE TITLE
web-ext run -p <> does not preserve user.js settings

### ISSUE THREAD

**Issue by lutostag** [mozilla/web-ext#870]
### Is this a bug or feature request?
Bug

### What is the current behavior?
user.js settings are not taken from --firefox-profile at all, instead they are directly overwritten with just the ones in [preferences.js](https://github.com/mozilla/web-ext/blob/master/src/firefox/preferences.js#L22)
Repro:
```
mkdir test_profile
echo 'user_pref("marionette.defaultPrefs.port", 34209);' > test_profile/user.js
yarn run web-ext run -p test_profile # --keep-profile-changes # is helpful for testing
# exit firefox
grep "marionette.defaultPrefs.port" test_profile/user.js
# is not found, or look in about:config for the setting which isnt there
```
Note that the preferences are ignored even without keep-changes, they will just be copied to a tmpdir though, so harder to track down.

This is an issue for me because I am trying to get a selenium environment up and running with my extension installed via web-ext. [WIP branch here](https://github.com/lutostag/web-ext/tree/selenium_arg_passthrough) I have everything tied together with an [almost working example](https://github.com/lutostag/webextension-formsave). This is basically my attempt at #5 for true e2e testing without stubs.

### What is the expected or desired behavior?
That preferences of a profile are correctly merged with the given preferences.js not entirely ignored and lost.

### Version information (for bug reports)

* **Firefox version**: Mozilla Firefox 52.0
* **Your OS and version**: Ubuntu 16.10
* Paste the output of these commands:

````
$ node --version && npm --version && yarn run web-ext --version
v6.10.0
3.10.10
0.21.3
````

**Comment by rpl** [comment]
Hi @lutostag, 
I think that you are right: the "user.js" file is currently completely overwritten with the "user.js" file generated by the 'firefox-profile' npm package (which is one of the web-ext dependencies).

Nevertheless, the scenario described above can be achieved using the "--pref" command line option (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--pref): 

by using this option we can ask "web-ext run" to customize one or more preferences (by repeating the --pref option), and they will be written in the "user.js" file alongside with the preferences needed by "web-ext run" itself to work correctly, e.g.:

```
web-ext run --pref marionette.defaultPrefs.port=34209
```

should set the marionette preference mentioned above.

Let me know if the `--pref` is able to cover your scenario.

btw, thanks for sharing your experiments related to functional testing a webextension, it is definitely a scenario that we would like to make as easy as possible.

**Comment by lutostag** [comment]
Yeah, that was my first thought too, but unfortunately selenium sets the following user.js (http://pastebin.com/C9uBRtwb) so there are ~82 settings and the only way to get them is to introduce a shim layer between selenium and web-ext which would just parse the user.js and pass it along as a crazy long string of args. Figured it was best to fix it here at the source.

If you are open for PRs on the subject, I believe I can tackle it. My method would be to abuse/extend getProfile() for useProfle and copyProfile to pass the user.js as extra customPrefs. Would that be reasonable or would you prefer a different approach?

**Comment by rpl** [comment]
I totally agree with you that ~82 are really too many preferences to set from the command line.

We are absolutely happy to discuss about this subject further, as well as new opened PRs related to it (this is definitely a use case that we want to cover, we just need to decide to agree on the approach, and how it would be better to fix the related issues).

As an example, in my opinion we have a bug that should be fixed in the `firefox-profile` dependency (so that we can support a `copyProfile` mode that doesn't completely overwrite the "user.js" file) and a "web-ext" feature (being able to set all the preferences needed by selenium without passing them on the command line).

This feature seems very similar to the feature request described in #715 (e.g. something like "web-ext run --prefs-set=selenium", similarly to how a "web-ext run --prefs-set=ateam" would work), and I'm also wondering if the config file support (which is not yet complete, but once it is, it is going to support loading configuration using a javascript nodejs module file, #730).

**Comment by lutostag** [comment]
Now that its fixed upstream it works with --keep-profile-changes, but not when copying a profile to a different temporary directory first. But I'm unblocked for now. Thanks for the pointers.

**Comment by kumar303** [comment]
I just merged https://github.com/mozilla/web-ext/pull/872 -- does that close this issue? Here are instructions for how to install web-ext from master: https://github.com/mozilla/web-ext/#installation-from-source

**Comment by lutostag** [comment]
Yes, the above fixed it. Thanks!
