### ISSUE TITLE
ZIP file generated by `web-ext build` fails to load in about:debugging

### ISSUE THREAD

**Issue by matthewjwein** [mozilla/web-ext#891]
### Is this a bug or feature request?
bug

### What is the current behavior?
STR:
1.) run `web-ext build` for any valid extension
2.) try loading the xpi in `about:debugging`
3.) the error "There was an error during installation: Directory /Users/<user-name>/Downloads/<extension-name>/web-ext-artifacts does not contain a valid install manifest" is displayed.

### What is the expected or desired behavior?
The addon should load without an error.

### Version information (for bug reports)
firefox version: confirmed on 52.0.2 and 55.0a1
web-ext version: 1.8.1
node: 6.10.0
npm: 3.10.10
node --version && npm --version && web-ext --version

**Comment by rpl** [comment]
Unfortunately the issue is not on the "web-ext CLI" side: 
if you just rename the ".zip" file into ".xpi", without any changes to the file content, the extension is loaded correctly from the "about:debugging" page.

The choice of building zip files is due to be able to submit the same generated file on both the Mozilla and Chrome extensions store websites.

The only reasonable workaround possible from the "web-ext CLI" side has been already filed as #393 (to be able to specify a file extension in the "web-ext build" command).

A better solution can be to change the "about:debugging" page on the Firefox side to make it able to recognize and install the zip file as WebExtensions as we did for the "about:addons" page in Bug 1328624.

**Comment by kumar303** [comment]
> firefox version: confirmed on 52.0.2 and 55.0a1

Thanks for reporting this @matthewjwein ! This bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1328624) says it was fixed in Firefox 54. Could you check out why it wasn't fixed for you? You said you tested in 55.0a1. Maybe that bug needs to be re-opened or a new one filed?

**Comment by rpl** [comment]
@kumar303 Bug 1328624 fixed a similar issue in the about:addons page, but it still not work from the about:debugging page.

@matthewjwein filed a new bug for it (https://bugzilla.mozilla.org/show_bug.cgi?id=1353861)
