### ISSUE TITLE
web-ext changes discoverURL

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#895]
In web-ext the run command changes discoverURL to this:

https://github.com/mozilla/web-ext/blob/a644ce08a21f67022354b4ac61d99081c14c874e/src/firefox/preferences.js#L62-L64

Which confused me because I ran web-ext, opened up about:addons and got gitlab:

<img width="1266" alt="screenshot 2017-04-10 13 25 34" src="https://cloud.githubusercontent.com/assets/74699/24881253/19b58e86-1df2-11e7-8efd-7d6148ca2586.png">

Ok, well I got gitlab because I'm running a gitlab instance on my localhost. I'm not quite sure why we are changing this though, could it be for testing?

**Comment by kumar303** [comment]
Oh, huh, those prefs were copied from jpm. I bet it was aimed at automated testing but we don't do that (and don't plan to do that) with `web-ext run` so I think we can stop changing all of those prefs (blocklist included).

**Comment by rpl** [comment]
@kumar303 is right, this preference was set from the previous addon development tools for a long time (even before jpm, cfx was already setting the same pref: http://searchfox.org/mozilla-central/rev/624d25b2980cf5f83452b040e6d664460f9b7ec5/addon-sdk/source/python-lib/cuddlefish/prefs.py#81).

This preference is definitely related to automated testing needs, in particular while running the mozilla-central mochitests, the test exits with a failure on any request to a non-local ip address (and cfx is still part of the jetpack mochitest test suite on mozilla-central).

I totally agree with @kumar303, we can safely remove it from the preferences that we set by default, because in our most common usage scenario (the "an addon developer is using web-ext to develop and test its webextension" scenario) is not really needed and it can be probably confusing to the user.

If for other usage scenario a user needs to set this preference, it is still possible by using the "--pref" command line option.

**Comment by andymckay** [comment]
Sounds good. If we ever implement a `web-ext test` mode, we can add these prefs back in then.

**Comment by jvillalobos** [comment]
Mentor: @kumar303

**Comment by tushararora** [comment]
Hi @kumar303. Can I work on this issue?

**Comment by kumar303** [comment]
Hi @tushararora , sure! This is free to work on. After reading through the [contributor guide](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md) let me know if you need any help getting started. The pref to change is here but there are a couple others we can clean up. https://github.com/mozilla/web-ext/blob/master/src/firefox/preferences.js#L63

**Comment by tushararora** [comment]
Sounds great! Looks like `extensions.update.url` and `extensions.blocklist.url` can also be removed . Can you let me know if there is any black box test that I can try to check if its working?

**Comment by kumar303** [comment]
There aren't any functional tests for this feature. To test that you made the right change, you could build a [development version](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#build-web-ext) with your patch and do [web-ext run](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) within one of these [examples](https://github.com/mdn/webextensions-examples/) then visit `about:addons` as described in this bug report.

**Comment by kumar303** [comment]
Thanks @tushararora ! The patch in https://github.com/mozilla/web-ext/pull/914 resets the discovery pane (I think). @andymckay let us know if this solves it or not.

**Comment by tushararora** [comment]
I tested it with a local server and it worked fine i.e. it loaded the default discoveryUrl in firefox.

Thanks a lot @kumar303. You are awesome! I am overwhelmed by the way you people welcome new contributors. Look forward to work on more issues.
